FROM mcr.microsoft.com/mssql/server:2019-latest

# Switch to root user
USER root

# Allow unencrypted connections by configuring mssql.conf
RUN mkdir -p /var/opt/mssql
COPY mssql.conf /var/opt/mssql/mssql.conf

# Expose SQL Server port
EXPOSE 1433

# Entry point
ENTRYPOINT ["/opt/mssql/bin/sqlservr"]